{
  "uid" : "9dbe4fa45d7e8794",
  "name" : "UnknownTestCase",
  "title" : "Unknown test case",
  "time" : {
    "start" : 1460649914870,
    "stop" : 1460649914870,
    "duration" : 0
  },
  "summary" : {
    "attachments" : 0,
    "steps" : 0
  },
  "failure" : {
    "message" : "failed",
    "stackTrace" : "suite2\\test_demo.py:9: in <module>\n    @pytest.mark.webtest\nE   TypeError: 'TestCase' object is not callable"
  },
  "description" : {
    "value" : "This is the tests collection phase. Failures are modules that failed to collect.",
    "type" : "TEXT"
  },
  "severity" : "NORMAL",
  "status" : "BROKEN",
  "testId" : null,
  "suite" : {
    "uid" : "f64b5257a4ebc33e",
    "name" : "test_collection_phase",
    "title" : "Collection phase"
  },
  "steps" : [ ],
  "attachments" : [ ],
  "issues" : [ ],
  "labels" : [ {
    "name" : "suite-title",
    "value" : "Collection phase"
  }, {
    "name" : "suite-name",
    "value" : "test_collection_phase"
  } ],
  "parameters" : [ ]
}